version: "3"

services:
  bank-transaction:
    container_name: bank-transaction-app
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    command: fresh
    volumes:
      - .:/app
#    depends_on:
#      - bank-transaction-mysql

  bank-transaction-mysql:
    container_name: bank-transaction-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: "dev"
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:rw