version: "3"

services:
  app:
    container_name: bank-transaction-app
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    command: fresh
#    network_mode: host
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    container_name: "bank-transaction-mysql"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: "bank-transaction"
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:rw